// Gegenleistungs-Karten aus dem Arbeitsplan. s: true = anzüglich (per Schalter ausblendbar)
const STAGES = {
  1: { name: 'Stufe 1', label: 'Kleinigkeit', hint: 'schnell erledigt, eher Geste' },
  2: { name: 'Stufe 2', label: 'Einsatz', hint: 'kostet einen Abend oder etwas Überwindung' },
  3: { name: 'Stufe 3', label: 'Hardcore', hint: 'aufwendig, peinlich oder sehr verwöhnend' },
  4: { name: 'Stufe 4', label: 'Boss-Level', hint: 'das volle Programm' },
  team: { name: 'Team', label: 'Team-Belohnung', hint: 'für euch beide' },
};
const CARDS = {
  1: [
    { t: '24 Stunden lang den Gewinner mit einem Ehrentitel ansprechen, z. B. „Eure Hoheit der Hüftstreckung“ oder „Bizeps-Baron“.' },
    { t: 'Der Gewinner bestimmt den nächsten Film oder die nächste Serie, ohne Widerspruch.' },
    { t: 'Dem Gewinner den nächsten Wecksong aussuchen lassen – und ihn morgen früh tatsächlich einstellen.' },
    { t: 'Eine spontane Laudatio auf den Gewinner halten, mindestens drei übertriebene Superlative Pflicht.' },
    { t: 'Den besten Bissen auf dem Teller kampflos an den Gewinner abtreten.' },
    { t: 'High Five, Verbeugung und ein lautstarkes „Respekt!“ – öffentlich, auch vor Zeugen.' },
    { t: '5 Minuten Nacken- oder Fußmassage.', s: true },
    { t: 'Ein Kuss-Gutschein, 24 Stunden lang jederzeit auf Zuruf einlösbar.', s: true },
    { t: 'Ein handgeschriebener Flirt-Zettel, irgendwo versteckt, wo der Gewinner ihn findet.', s: true },
  ],
  2: [
    { t: 'Wochenendfrühstück zubereiten, inklusive Tisch decken.' },
    { t: 'Einen Abend lang Butler oder Butlerin spielen: Geschirrtuch über dem Arm, jede Antwort beginnt mit „Sehr wohl“.' },
    { t: '10 Komplimente am Stück, keins darf sich wiederholen.' },
    { t: '24 Stunden lang ein vom Gewinner gewähltes, absurdes Selfie als Profilbild im Familienchat.' },
    { t: 'Eine kleine Schnitzeljagd durch die Wohnung vorbereiten, am Ziel wartet eine süße Überraschung.' },
    { t: 'Einen handgeschriebenen Liebesbrief verfassen und dem Gewinner laut vorlesen.' },
    { t: 'Der Gewinner sucht ein möglichst unvorteilhaftes Foto vom Verlierer aus, das eine Woche lang Hintergrundbild auf dessen Handy bleibt.' },
    { t: '15 Minuten Massage mit Öl, der Gewinner wählt die Körperregion.', s: true },
    { t: 'Der Gewinner wählt das Outfit, das der Verlierer beim nächsten Abend zu Hause trägt.', s: true },
    { t: 'Ein Bad oder eine Dusche mit Kerzen vorbereiten, Begleitung inklusive.', s: true },
  ],
  3: [
    { t: 'Candle-Light-Dinner mit 3 Gängen kochen, Menükarte handgeschrieben.' },
    { t: 'Ein Gedicht über den Po beziehungsweise die Oberarme des Gewinners schreiben und feierlich vortragen.' },
    { t: 'Einen ganzen Tag lang jede Treppe mit Ausfallschritten hochgehen.' },
    { t: 'Ein Abend, an dem der Gewinner alles entscheidet: Essen, Programm, Schlafenszeit.' },
    { t: 'Ein „Ja-Gutschein“: Die nächste Bitte wird ohne Diskussion erfüllt, im Rahmen des Anstands.' },
    { t: 'Eine Woche lang jeden Morgen das Bett machen.' },
    { t: 'Eine improvisierte Tanzperformance zum Lieblingssong des Gewinners aufführen, volle Hingabe, keine halben Sachen.' },
    { t: 'Einen Loblied-Rap auf den Gewinner freestylen, mindestens 30 Sekunden, Reime sind Pflicht.' },
    { t: '30 Minuten Verwöhn-Massage, Musik und Licht wählt der Gewinner.', s: true },
  ],
  4: [
    { t: 'Eine Liebeserklärung als Sprachnachricht im Stil eines Fußballkommentators, mindestens 60 Sekunden.' },
    { t: 'Ein Überraschungsdate planen und bezahlen, der Gewinner erfährt vorher nur die Uhrzeit.' },
    { t: 'Einen ganzen Tag als persönlicher Assistent des Gewinners fungieren: Termine, Snacks, gute Laune, alles auf Abruf.' },
    { t: 'Ein selbst gedrehtes Mini-Musikvideo für den Gewinner produzieren, mit Kostüm und eigener Choreografie.' },
    { t: 'Eine Überraschungs-Unternehmung für einen halben Tag organisieren, das Ziel bleibt bis zur Abfahrt geheim.' },
    { t: 'Einen Ehrenpokal basteln und dem Gewinner bei einer kleinen Zeremonie mit Dankesrede überreichen.' },
    { t: 'Der Gewinner schreibt das Drehbuch für einen gemeinsamen Abend, der Verlierer spielt mit.', s: true },
    { t: 'Verführungsabend inszenieren: Deko, Musik, Outfit, alles vom Verlierer vorbereitet.', s: true },
  ],
  team: [
    { t: 'Ein Ausflug am Wochenende, den beide abwechselnd planen.' },
    { t: 'Gemeinsam ein neues Rezept ausprobieren und beim Kochen laut die passende Playlist mitsingen.' },
    { t: 'Ein Spieleabend mit dem Lieblingsspiel, Verlierer der ersten Runde räumt danach auf.' },
    { t: 'Zu einer Veranstaltung gehen, die schon lange auf der gemeinsamen Liste steht.' },
    { t: 'Ein Ausflug in die Natur mit Picknick, Handys bleiben in der Tasche.' },
    { t: 'Filmabend mit Lieblingssnacks, Decke und Kerzen, ganz ohne Ablenkung von außen.' },
    { t: 'Ein neues Café oder Restaurant in der Stadt ausprobieren, das noch keiner von euch kennt.' },
  ],
};
